import type { Wafer } from '../core/wafer.js';
import type { Die } from '../core/dies.js';
import type { Reticle } from '../core/reticle.js';
import type { DieMetadata, WaferMetadata } from '../core/metadata.js';
import { rotatePoint } from '../core/transforms.js';
import { contrastTextColor } from './colorMap.js';
import { getColorScheme } from './colorSchemes.js';

export type PlotMode = 'value' | 'hardbin' | 'softbin' | 'stackedValues' | 'stackedBins';

interface Point {
  x: number;
  y: number;
}

export interface SceneRect {
  x: number;
  y: number;
  width: number;
  height: number;
  fill: string | number;
  type: 'hardbin' | 'softbin' | 'value' | 'stacked';
  stack?: number[];
  metadata?: DieMetadata;
  path: string;
}

export interface SceneText {
  x: number;
  y: number;
  text: string;
  fontSize: number;
  color: string;
  align: 'center';
}

export interface SceneHoverPoint {
  x: number;
  y: number;
  text: string;
}

export interface SceneOverlay {
  kind: 'wafer-boundary' | 'reticle' | 'probe-path' | 'ring-boundary' | 'quadrant-boundary' | 'xy-indicator';
  path: string;
  lineColor: string;
  lineWidth: number;
  fill?: string;
}

export interface Scene {
  rectangles: SceneRect[];
  hoverPoints: SceneHoverPoint[];
  texts: SceneText[];
  overlays: SceneOverlay[];
  plotMode: PlotMode;
  colorScheme: string;
  metadata: WaferMetadata | null;
  dies: Die[];
  /** Actual [min, max] of the value data used for color normalization. */
  valueRange: [number, number];
}

export interface SceneOptions {
  plotMode?: PlotMode;
  showText?: boolean;
  showReticle?: boolean;
  showProbePath?: boolean;
  ringCount?: number;
  showRingBoundaries?: boolean;
  showQuadrantBoundaries?: boolean;
  showXYIndicator?: boolean;
  dieGap?: number;
  /** Named colour scheme — any scheme registered via registerColorScheme(). Default: 'default'. */
  colorScheme?: string;
  highlightBin?: number;
  interactiveTransform?: { rotation?: number; flipX?: boolean; flipY?: boolean };
  /**
   * Explicit [min, max] for value colour normalization. When omitted the range
   * is auto-computed from the die values present in the scene.
   */
  valueRange?: [number, number];
  /**
   * Reticle rectangles to overlay on the map.
   * Generated by `generateReticleGrid` or the `reticle` option on `buildWaferMap`.
   */
  reticles?: Reticle[];
}

/** @deprecated Use {@link SceneOptions} */
export type BuildSceneOptions = SceneOptions;

interface TransformState {
  rotation: number;
  flipX: boolean;
  flipY: boolean;
}

interface ColorFns {
  forValue: (t: number) => string;
  forHardBin: (bin: number) => string;
  forSoftBin: (bin: number) => string;
}

const PARTIAL_DIE_FILL = '#d3d6db';
const DIM_FILL = '#e8e9ea';
const EDGE_EXCLUDED_FILL = '#eceef0';

function normalizeTransform(
  wafer: Wafer,
  interactiveTransform: SceneOptions['interactiveTransform']
): TransformState {
  return {
    rotation: wafer.orientation + (interactiveTransform?.rotation ?? 0),
    flipX: interactiveTransform?.flipX ?? false,
    flipY: interactiveTransform?.flipY ?? false,
  };
}

function transformVector(dx: number, dy: number, transform: TransformState): Point {
  const rad = (transform.rotation * Math.PI) / 180;
  const cos = Math.cos(rad);
  const sin = Math.sin(rad);
  let x = dx * cos - dy * sin;
  let y = dx * sin + dy * cos;

  if (transform.flipX) x = -x;
  if (transform.flipY) y = -y;

  return { x, y };
}

function toPath(points: Point[]): string {
  return `${points.map((point, index) => `${index === 0 ? 'M' : 'L'} ${point.x} ${point.y}`).join(' ')} Z`;
}

function polylinePath(points: Point[], close = false): string {
  if (!points.length) return '';
  const path = points.map((point, index) => `${index === 0 ? 'M' : 'L'} ${point.x} ${point.y}`).join(' ');
  return close ? `${path} Z` : path;
}

function transformPoint(point: Point, center: Point, transform: TransformState): Point {
  let next = transform.rotation ? rotatePoint(point.x, point.y, transform.rotation, center.x, center.y) : point;
  if (transform.flipX) next = { x: 2 * center.x - next.x, y: next.y };
  if (transform.flipY) next = { x: next.x, y: 2 * center.y - next.y };
  return next;
}

/**
 * Returns the boundary point at `angle` for a wafer with an orientation flat
 * (chord cut).  V-notch wafers are handled separately in buildBoundaryOverlay.
 */
function boundaryPointAtAngle(wafer: Wafer, angle: number): Point {
  const { center, radius, notch } = wafer;
  let x = center.x + radius * Math.cos(angle);
  let y = center.y + radius * Math.sin(angle);

  if (!notch) return { x, y };

  const chordDist = Math.sqrt(radius ** 2 - (notch.length / 2) ** 2);
  const halfLen   = notch.length / 2;
  const dx = x - center.x;
  const dy = y - center.y;

  if (notch.type === 'bottom' && dy < -chordDist) {
    y = center.y - chordDist;
    x = center.x + Math.max(-halfLen, Math.min(halfLen, dx));
  } else if (notch.type === 'top' && dy > chordDist) {
    y = center.y + chordDist;
    x = center.x + Math.max(-halfLen, Math.min(halfLen, dx));
  } else if (notch.type === 'left' && dx < -chordDist) {
    x = center.x - chordDist;
    y = center.y + Math.max(-halfLen, Math.min(halfLen, dy));
  } else if (notch.type === 'right' && dx > chordDist) {
    x = center.x + chordDist;
    y = center.y + Math.max(-halfLen, Math.min(halfLen, dy));
  }

  return { x, y };
}

function rectanglePath(center: Point, width: number, height: number, transform: TransformState): string {
  const corners = [
    transformVector(-width / 2, -height / 2, transform),
    transformVector(width / 2, -height / 2, transform),
    transformVector(width / 2, height / 2, transform),
    transformVector(-width / 2, height / 2, transform),
  ].map((corner) => ({ x: center.x + corner.x, y: center.y + corner.y }));

  return toPath(corners);
}

function formatValueLabel(values: number[]): string {
  return values.map((value) => value.toFixed(values.length > 1 ? 2 : 3)).join(' / ');
}

function formatBinLabel(bins: number[]): string {
  return bins.map((bin) => String(bin)).join('|');
}

function fontSizeForDie(die: Die, text: string): number {
  const minSide = Math.max(1, Math.min(die.width, die.height));
  const widthBudget = die.width / Math.max(text.length, 1);
  return Math.max(8, Math.min(16, Math.round(Math.min(minSide * 0.55, widthBudget * 1.8))));
}

function buildHoverText(die: Die): string {
  const lines: string[] = [`Die (${die.i}, ${die.j})`];

  if (die.values?.length) lines.push(`Values: ${die.values.map((value) => value.toFixed(3)).join(' / ')}`);
  if (die.bins?.length) lines.push(`Bins: ${die.bins.map((bin) => `B${bin}`).join(' | ')}`);
  if (die.partial) lines.push('<i>partial die</i>');
  if (die.probeIndex !== undefined) lines.push(`Probe: #${die.probeIndex}`);

  if (die.metadata) {
    for (const [key, value] of Object.entries(die.metadata)) {
      if (value === undefined || value === null || key === 'customFields') continue;
      lines.push(`${key}: ${String(value)}`);
    }

    if (die.metadata.customFields) {
      for (const [key, value] of Object.entries(die.metadata.customFields)) {
        if (value === undefined || value === null) continue;
        lines.push(`${key}: ${String(value)}`);
      }
    }
  }

  return lines.join('<br>');
}

export function generateTextOverlay(
  dies: Die[],
  options: { plotMode: PlotMode; colorFns: ColorFns; normalize: (v: number) => number },
): SceneText[] {
  const { plotMode, colorFns, normalize } = options;
  return dies.flatMap((die) => {
    let text = '';
    let color = '#111111';

    if (plotMode === 'value') {
      if (!die.values?.length) return [];
      text = formatValueLabel([die.values[0]]);
      color = contrastTextColor(colorFns.forValue(normalize(die.values[0])));
    } else if (plotMode === 'hardbin') {
      const bin = die.bins?.[0];
      if (bin === undefined) return [];
      text = String(bin);
      color = contrastTextColor(colorFns.forHardBin(bin));
    } else if (plotMode === 'softbin') {
      const bin = die.bins?.[0];
      if (bin === undefined) return [];
      text = String(bin);
      color = contrastTextColor(colorFns.forSoftBin(bin));
    } else if (plotMode === 'stackedBins') {
      if (!die.bins?.length) return [];
      text = formatBinLabel(die.bins);
      color = contrastTextColor(colorFns.forHardBin(die.bins[Math.floor(die.bins.length / 2)]));
    } else {
      if (!die.values?.length) return [];
      text = formatValueLabel(die.values);
      color = contrastTextColor(colorFns.forValue(normalize(die.values[Math.floor(die.values.length / 2)])));
    }

    return [{
      x: die.x,
      y: die.y,
      text,
      fontSize: fontSizeForDie(die, text),
      color,
      align: 'center',
    }];
  });
}

/**
 * Notch direction angle in radians.
 * Wafer convention: bottom notch points downward (−Y), which is angle −π/2.
 */
function notchAngle(type: 'top' | 'bottom' | 'left' | 'right'): number {
  if (type === 'top')    return  Math.PI / 2;
  if (type === 'bottom') return -Math.PI / 2;
  if (type === 'left')   return  Math.PI;
  return 0; // right
}

/**
 * Build the wafer boundary overlay, choosing between two rendering modes:
 *
 * - **Flat** (≤ 150 mm): straight chord cut — `boundaryPointAtAngle` handles it.
 * - **V-notch** (> 150 mm): three explicit points (entry → apex → exit) are
 *   spliced into the uniform circle trace so the notch renders as a sharp
 *   triangular indentation (~3.5 mm wide, ~1.25 mm deep — SEMI M1 standard).
 */
function buildBoundaryOverlay(wafer: Wafer, transform: TransformState, steps = 720): SceneOverlay[] {
  const { center, radius, notch } = wafer;

  // Determine rendering style from diameter — same threshold used in resolveNotch.
  const isVNotch = notch !== undefined && wafer.diameter > 150;

  if (!isVNotch) {
    // Flat / no alignment feature — uniform angle sweep with chord clamping.
    const points: Point[] = [];
    for (let index = 0; index <= steps; index++) {
      const angle = (2 * Math.PI * index) / steps;
      points.push(transformPoint(boundaryPointAtAngle(wafer, angle), center, transform));
    }
    return [{ kind: 'wafer-boundary', path: polylinePath(points, true), lineColor: '#111111', lineWidth: 2 }];
  }

  // V-notch: build circle, then splice in the triangular indentation.
  // SEMI M1: half-width at surface ≈ 1.75 mm, depth ≈ 1.25 mm.
  const notchDepth     = 1.25;
  const notchHalfWidth = notch.length; // set by createWafer = 1.75 for large wafers
  const θ0             = notchAngle(notch.type);
  const Δ              = Math.atan2(notchHalfWidth, radius); // angular half-span (~0.67° for 300 mm)
  const apexRadius     = radius - notchDepth;

  // Collect uniform circle points, skipping any that fall inside the notch zone.
  const points: Point[] = [];
  let notchInserted = false;

  for (let index = 0; index <= steps; index++) {
    const angle = (2 * Math.PI * index) / steps;

    // Normalise angle difference to (−π, π].
    let dθ = angle - θ0;
    while (dθ >  Math.PI) dθ -= 2 * Math.PI;
    while (dθ < -Math.PI) dθ += 2 * Math.PI;

    if (Math.abs(dθ) <= Δ) {
      // Inside the notch arc — insert V geometry once at this crossing.
      if (!notchInserted) {
        notchInserted = true;
        const entry = { x: center.x + radius * Math.cos(θ0 - Δ), y: center.y + radius * Math.sin(θ0 - Δ) };
        const apex  = { x: center.x + apexRadius * Math.cos(θ0), y: center.y + apexRadius * Math.sin(θ0) };
        const exit_ = { x: center.x + radius * Math.cos(θ0 + Δ), y: center.y + radius * Math.sin(θ0 + Δ) };
        points.push(
          transformPoint(entry, center, transform),
          transformPoint(apex,  center, transform),
          transformPoint(exit_, center, transform),
        );
      }
      continue;
    }

    points.push(transformPoint({ x: center.x + radius * Math.cos(angle), y: center.y + radius * Math.sin(angle) }, center, transform));
  }

  return [{ kind: 'wafer-boundary', path: polylinePath(points, true), lineColor: '#111111', lineWidth: 2 }];
}

function buildRingOverlays(wafer: Wafer, transform: TransformState, ringCount: number, steps = 360): SceneOverlay[] {
  const overlays: SceneOverlay[] = [];
  const safeRingCount = Math.max(1, Math.floor(ringCount));

  for (let ring = 1; ring < safeRingCount; ring++) {
    const radius = (wafer.radius * ring) / safeRingCount;
    const points: Point[] = [];

    for (let index = 0; index <= steps; index++) {
      const angle = (2 * Math.PI * index) / steps;
      const localPoint = {
        x: wafer.center.x + radius * Math.cos(angle),
        y: wafer.center.y + radius * Math.sin(angle),
      };
      points.push(transformPoint(localPoint, wafer.center, transform));
    }

    overlays.push({
      kind: 'ring-boundary',
      path: polylinePath(points, true),
      lineColor: 'rgba(255,255,255,0.7)',
      lineWidth: 1.5,
    });
  }

  return overlays;
}

function buildQuadrantOverlays(wafer: Wafer, transform: TransformState): SceneOverlay[] {
  const angles = [0, Math.PI / 2];

  return angles.map((angle) => {
    const start = transformPoint(boundaryPointAtAngle(wafer, angle), wafer.center, transform);
    const end = transformPoint(boundaryPointAtAngle(wafer, angle + Math.PI), wafer.center, transform);
    return {
      kind: 'quadrant-boundary',
      path: polylinePath([start, end]),
      lineColor: 'rgba(255,255,255,0.7)',
      lineWidth: 1.5,
    };
  });
}

function buildReticleOverlays(reticles: Reticle[], wafer: Wafer, transform: TransformState): SceneOverlay[] {
  return reticles.map((reticle) => {
    const rotatedCenter = transform.rotation
      ? rotatePoint(reticle.x, reticle.y, transform.rotation, wafer.center.x, wafer.center.y)
      : { x: reticle.x, y: reticle.y };

    const transformedCenter = {
      x: transform.flipX ? 2 * wafer.center.x - rotatedCenter.x : rotatedCenter.x,
      y: transform.flipY ? 2 * wafer.center.y - rotatedCenter.y : rotatedCenter.y,
    };

    return {
      kind: 'reticle',
      path: rectanglePath(transformedCenter, reticle.width, reticle.height, transform),
      lineColor: 'rgba(0,100,220,0.45)',
      lineWidth: 1,
      fill: 'rgba(0,0,0,0)',
    };
  });
}

function buildProbeOverlay(dies: Die[]): SceneOverlay[] {
  const ordered = dies
    .filter((die) => die.probeIndex !== undefined)
    .sort((left, right) => (left.probeIndex ?? 0) - (right.probeIndex ?? 0));

  if (!ordered.length) return [];

  return [{
    kind: 'probe-path',
    path: polylinePath(ordered.map((die) => ({ x: die.x, y: die.y }))),
    lineColor: 'rgba(220,80,0,0.55)',
    lineWidth: 1,
  }];
}

function pushDieRectangles(
  rectangles: SceneRect[],
  die: Die,
  plotMode: PlotMode,
  transform: TransformState,
  gap: number,
  colorFns: ColorFns,
  highlightBin: number | undefined,
  normalize: (v: number) => number
): void {
  const rw = die.width - gap;
  const rh = die.height - gap;

  if (die.partial) {
    rectangles.push({
      x: die.x, y: die.y, width: rw, height: rh,
      fill: PARTIAL_DIE_FILL, type: 'stacked', metadata: die.metadata,
      path: rectanglePath(die, rw, rh, transform),
    });
    return;
  }

  if (die.edgeExcluded) {
    rectangles.push({
      x: die.x, y: die.y, width: rw, height: rh,
      fill: EDGE_EXCLUDED_FILL, type: 'stacked', metadata: die.metadata,
      path: rectanglePath(die, rw, rh, transform),
    });
    return;
  }

  if (highlightBin !== undefined && die.bins?.[0] !== highlightBin) {
    rectangles.push({
      x: die.x, y: die.y, width: rw, height: rh,
      fill: DIM_FILL, type: 'hardbin', metadata: die.metadata,
      path: rectanglePath(die, rw, rh, transform),
    });
    return;
  }

  if (plotMode === 'value') {
    const value = die.values?.[0];
    const fill = value !== undefined ? colorFns.forValue(normalize(value)) : '#d6d9dd';
    rectangles.push({
      x: die.x, y: die.y, width: rw, height: rh,
      fill, type: 'value', metadata: die.metadata,
      path: rectanglePath(die, rw, rh, transform),
    });
    return;
  }

  if (plotMode === 'hardbin') {
    const bin = die.bins?.[0] ?? 0;
    rectangles.push({
      x: die.x, y: die.y, width: rw, height: rh,
      fill: colorFns.forHardBin(bin), type: 'hardbin', metadata: die.metadata,
      path: rectanglePath(die, rw, rh, transform),
    });
    return;
  }

  if (plotMode === 'softbin') {
    const bin = die.bins?.[0] ?? 0;
    rectangles.push({
      x: die.x, y: die.y, width: rw, height: rh,
      fill: colorFns.forSoftBin(bin), type: 'softbin', metadata: die.metadata,
      path: rectanglePath(die, rw, rh, transform),
    });
    return;
  }

  if (plotMode === 'stackedBins') {
    const bins = die.bins?.length ? die.bins : [0];
    const segmentWidth = rw / bins.length;

    bins.forEach((bin, index) => {
      const localX = -rw / 2 + segmentWidth * (index + 0.5);
      const offset = transformVector(localX, 0, transform);
      rectangles.push({
        x: die.x + offset.x, y: die.y + offset.y,
        width: segmentWidth, height: rh,
        fill: colorFns.forHardBin(bin), type: 'stacked', stack: [...bins], metadata: die.metadata,
        path: rectanglePath({ x: die.x + offset.x, y: die.y + offset.y }, segmentWidth, rh, transform),
      });
    });
    return;
  }

  const values = die.values?.length ? die.values : [0];
  const segmentWidth = rw / values.length;

  values.forEach((value, index) => {
    const localX = -rw / 2 + segmentWidth * (index + 0.5);
    const offset = transformVector(localX, 0, transform);
    rectangles.push({
      x: die.x + offset.x, y: die.y + offset.y,
      width: segmentWidth, height: rh,
      fill: colorFns.forValue(normalize(value)), type: 'stacked', stack: [...values], metadata: die.metadata,
      path: rectanglePath({ x: die.x + offset.x, y: die.y + offset.y }, segmentWidth, rh, transform),
    });
  });
}

function buildXYIndicatorOverlay(
  wafer: Wafer,
  transform: TransformState,
  texts: SceneText[]
): SceneOverlay[] {
  // Anchor is fixed at the bottom-left corner in data space (outside the wafer circle).
  // 0.9 per axis → distance ≈ 1.27 × radius: outside the circle but inside the chart area.
  // Do NOT transform the anchor — it stays in the corner regardless of wafer rotation/flip.
  // Only the arrow directions rotate, so they still correctly indicate the data axes.
  const len = wafer.radius * 0.15;
  const anchor = {
    x: wafer.center.x - wafer.radius * 0.9,
    y: wafer.center.y - wafer.radius * 0.9,
  };
  const xDir = transformVector(len, 0, transform);
  const yDir = transformVector(0, len, transform);
  const xTip = { x: anchor.x + xDir.x, y: anchor.y + xDir.y };
  const yTip = { x: anchor.x + yDir.x, y: anchor.y + yDir.y };

  texts.push(
    { x: xTip.x + xDir.x * 0.35, y: xTip.y + xDir.y * 0.35, text: '+X', fontSize: 10, color: '#cc3300', align: 'center' },
    { x: yTip.x + yDir.x * 0.35, y: yTip.y + yDir.y * 0.35, text: '+Y', fontSize: 10, color: '#0044cc', align: 'center' },
  );

  return [
    { kind: 'xy-indicator', path: polylinePath([anchor, xTip]), lineColor: '#cc3300', lineWidth: 2 },
    { kind: 'xy-indicator', path: polylinePath([anchor, yTip]), lineColor: '#0044cc', lineWidth: 2 },
  ];
}

/**
 * Build a renderer-agnostic scene from a wafer, dies, and display options.
 *
 * ```ts
 * buildScene(wafer, dies, { plotMode: 'hardbin', reticles })
 * ```
 */
export function buildScene(
  wafer: Wafer,
  dies: Die[],
  options: SceneOptions = {},
): Scene {
  const reticles = options.reticles ?? [];

  const {
    plotMode = 'value',
    showText = false,
    showReticle = false,
    showProbePath = false,
    ringCount = 4,
    showRingBoundaries = false,
    showQuadrantBoundaries = false,
    showXYIndicator = false,
    dieGap = 1,
    colorScheme = 'color',
    highlightBin,
    interactiveTransform,
    valueRange: explicitRange,
  } = options;

  const scheme = getColorScheme(colorScheme);

  // Auto-range soft bins so the gradient spans the actual bin values in the data.
  let maxSoftBin = 1;
  if (plotMode === 'softbin') {
    for (const die of dies) {
      const b = die.bins?.[0] ?? 0;
      if (b > maxSoftBin) maxSoftBin = b;
    }
  }

  const colorFns: ColorFns = {
    forValue: scheme.forValue,
    forHardBin: scheme.forBin,
    forSoftBin: (bin) => scheme.forValue(Math.max(0, Math.min(1, bin / maxSoftBin))),
  };

  // Compute value range for normalization (used by value / stackedValues modes).
  // For 'value' mode only values[0] is rendered — range against that channel only.
  // For 'stackedValues' all channels are rendered side-by-side — range across all.
  let vMin: number;
  let vMax: number;
  if (explicitRange) {
    [vMin, vMax] = explicitRange;
  } else {
    let lo = Infinity, hi = -Infinity;
    for (const die of dies) {
      const vals = die.values ?? [];
      const candidates = plotMode === 'stackedValues' ? vals : vals.slice(0, 1);
      for (const v of candidates) {
        if (v < lo) lo = v;
        if (v > hi) hi = v;
      }
    }
    vMin = isFinite(lo) ? lo : 0;
    vMax = isFinite(hi) ? hi : 1;
  }
  if (vMin === vMax) vMax = vMin + 1;
  const normalize = (v: number) => Math.max(0, Math.min(1, (v - vMin) / (vMax - vMin)));

  const transform = normalizeTransform(wafer, interactiveTransform);

  // Cap the visual kerf gap at 12 % of the smallest die dimension so that
  // normalised-unit scenes (die pitch ≈ 1) remain visible. No effect for
  // standard 10 mm dies: min(1, 10 × 0.12 = 1.2) = 1.
  const minDim = dies.reduce((m, d) => Math.min(m, d.width, d.height), Infinity);
  const gap = Number.isFinite(minDim) ? Math.min(dieGap, minDim * 0.12) : dieGap;

  const rectangles: SceneRect[] = [];
  const hoverPoints: SceneHoverPoint[] = [];
  // Pre-transformed dies — positions rotated/flipped around wafer centre.
  // Only the x,y centre moves; die.i/j/width/height/bins/values are unchanged.
  const transformedDies = (transform.rotation || transform.flipX || transform.flipY)
    ? dies.map(d => {
        const tp = transformPoint({ x: d.x, y: d.y }, wafer.center, transform);
        return { ...d, x: tp.x, y: tp.y };
      })
    : dies;

  for (const tdie of transformedDies) {
    pushDieRectangles(rectangles, tdie, plotMode, transform, gap, colorFns, highlightBin, normalize);
    hoverPoints.push({ x: tdie.x, y: tdie.y, text: buildHoverText(tdie) });
  }

  const texts: SceneText[] = showText ? generateTextOverlay(transformedDies, { plotMode, colorFns, normalize }) : [];
  const overlays = buildBoundaryOverlay(wafer, transform);

  if (showRingBoundaries) overlays.push(...buildRingOverlays(wafer, transform, ringCount));
  if (showQuadrantBoundaries) overlays.push(...buildQuadrantOverlays(wafer, transform));
  if (showReticle) overlays.push(...buildReticleOverlays(reticles, wafer, transform));
  if (showProbePath) overlays.push(...buildProbeOverlay(dies));
  if (showXYIndicator) overlays.push(...buildXYIndicatorOverlay(wafer, transform, texts));

  return {
    rectangles,
    hoverPoints,
    texts,
    overlays,
    plotMode,
    colorScheme,
    metadata: wafer.metadata ?? null,
    dies,
    valueRange: [vMin, vMax],
  };
}

// ── Die lookup helpers ────────────────────────────────────────────────────────

/**
 * Return a stable string key for a die — guaranteed format `"i,j"`.
 * Use this for Map keys and post-enrichment lookups instead of ad-hoc template literals.
 *
 * ```ts
 * const map = new Map(result.dies.map(d => [getDieKey(d), d]));
 * const die = map.get(getDieKey({ i: 3, j: -2 }));
 * ```
 */
export function getDieKey(die: { i: number; j: number }): string {
  return `${die.i},${die.j}`;
}

/**
 * Return the die that a Plotly click or hover event points to.
 *
 * The hover scatter trace stores one point per die, indexed parallel to
 * `scene.dies`.  Pass the raw Plotly event object directly.
 *
 * ```ts
 * chart.on('plotly_click', ev => {
 *   const die = getDieAtPoint(scene, ev);
 *   if (die) console.log(die.i, die.j, die.values, die.bins);
 * });
 * ```
 *
 * Returns `null` when the event doesn't resolve to a known die (e.g. click on
 * an overlay trace rather than the hover trace).
 */
export function getDieAtPoint(
  scene: Scene,
  plotlyEvent: { points?: Array<{ pointIndex?: number; curveNumber?: number }> },
): Die | null {
  const pt = plotlyEvent.points?.[0];
  if (!pt) return null;
  // The hover scatter is always trace 0.  Other traces (text, colorbar ref) are not dies.
  if (pt.curveNumber !== 0) return null;
  const idx = pt.pointIndex;
  if (idx === undefined || idx < 0 || idx >= scene.dies.length) return null;
  return scene.dies[idx];
}
